-- MySQL Script generated by MySQL Workbench
-- Mon Dec  5 20:00:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`tipofilme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`tipofilme` (
  `i_idCategoria_TipoFilme` INT NOT NULL,
  `s_genero_TipoFilme` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`i_idCategoria_TipoFilme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`filme` (
  `i_id_filme` INT NOT NULL,
  `s_titulo_filme` VARCHAR(30) NOT NULL,
  `s_nacionalidade_filme` VARCHAR(10) NOT NULL,
  `s_estudio_filme` VARCHAR(10) NOT NULL,
  `i_tipoFilme_filme` INT NOT NULL,
  `s_atores_filme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`i_id_filme`, `s_atores_filme`),
  INDEX `fk_tipoFilme` (`i_tipoFilme_filme` ASC) VISIBLE,
  CONSTRAINT `fk_tipoFilme`
    FOREIGN KEY (`i_tipoFilme_filme`)
    REFERENCES `cinema`.`tipofilme` (`i_idCategoria_TipoFilme`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`atores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`atores` (
  `i_id_ator` INT NOT NULL,
  `s_nome_ator` VARCHAR(20) NOT NULL,
  `atorescol` VARCHAR(45) NULL,
  PRIMARY KEY (`i_id_ator`, `s_nome_ator`),
  INDEX `fk_atores_filme1_idx` (`s_nome_ator` ASC) VISIBLE,
  CONSTRAINT `fk_atores_filme1`
    FOREIGN KEY (`s_nome_ator`)
    REFERENCES `cinema`.`filme` (`s_atores_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`tipocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`tipocliente` (
  `i_id_TCliente` INT NOT NULL,
  `s_desc_TCliente` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`i_id_TCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`sala` (
  `i_cod_sala` INT NOT NULL,
  `i_capa_sala` INT NOT NULL,
  `i_poltrona_sala` INT NOT NULL,
  `i_numero_sala` INT NOT NULL,
  PRIMARY KEY (`i_cod_sala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`secoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`secoes` (
  `i_cod_secoes` INT NOT NULL,
  `d_data_secoes` DATE NOT NULL,
  `h_hora_secoes` DATETIME NOT NULL,
  `i_TipoSala_secoes` INT NOT NULL,
  `filme_i_id_filme` INT NOT NULL,
  PRIMARY KEY (`i_cod_secoes`, `filme_i_id_filme`),
  INDEX `i_TipoSala_secoes` (`i_TipoSala_secoes` ASC) VISIBLE,
  INDEX `fk_secoes_filme1_idx` (`filme_i_id_filme` ASC) VISIBLE,
  CONSTRAINT `secoes_ibfk_1`
    FOREIGN KEY (`i_TipoSala_secoes`)
    REFERENCES `cinema`.`sala` (`i_cod_sala`),
  CONSTRAINT `fk_secoes_filme1`
    FOREIGN KEY (`filme_i_id_filme`)
    REFERENCES `cinema`.`filme` (`i_id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`ingressos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`ingressos` (
  `i_cod_ingresso` INT NOT NULL,
  `f_preco_ingresso` INT NOT NULL,
  `secoes_i_cod_secoes` INT NOT NULL,
  INDEX `fk_ingressos_secoes1_idx` (`secoes_i_cod_secoes` ASC) VISIBLE,
  CONSTRAINT `fk_ingressos_secoes1`
    FOREIGN KEY (`secoes_i_cod_secoes`)
    REFERENCES `cinema`.`secoes` (`i_cod_secoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`estreias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`estreias` (
  `i_idEstreia_est` INT NOT NULL,
  `d_dataEstreia_est` DATE NOT NULL,
  `ingressos_i_cod_ingresso` INT NOT NULL,
  PRIMARY KEY (`i_idEstreia_est`, `ingressos_i_cod_ingresso`),
  INDEX `fk_estreias_ingressos1_idx` (`ingressos_i_cod_ingresso` ASC) VISIBLE,
  CONSTRAINT `fk_estreias_ingressos1`
    FOREIGN KEY (`ingressos_i_cod_ingresso`)
    REFERENCES `cinema`.`ingressos` (`i_cod_ingresso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`lanches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`lanches` (
  `i_cod_lanche` INT NOT NULL,
  `f_preco_lanche` FLOAT NOT NULL,
  `i_quantidade_lanche` INT NOT NULL,
  `i_tipo_lanche` INT NOT NULL,
  PRIMARY KEY (`i_cod_lanche`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`comprar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`comprar` (
  `i_ingresso_comprar` INT NOT NULL,
  `i_lanches_comprar` INT NOT NULL,
  `i_estreia_comprar` INT NOT NULL,
  `checaBilhe_comprar` INT NOT NULL,
  PRIMARY KEY (`i_ingresso_comprar`, `i_lanches_comprar`, `i_estreia_comprar`, `checaBilhe_comprar`),
  INDEX `fk_comprar_estreias1_idx` (`i_estreia_comprar` ASC) VISIBLE,
  INDEX `fk_comprar_lanches1_idx` (`i_lanches_comprar` ASC) VISIBLE,
  CONSTRAINT `fk_comprar_estreias1`
    FOREIGN KEY (`i_estreia_comprar`)
    REFERENCES `cinema`.`estreias` (`i_idEstreia_est`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprar_lanches1`
    FOREIGN KEY (`i_lanches_comprar`)
    REFERENCES `cinema`.`lanches` (`i_cod_lanche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprar_ingressos1`
    FOREIGN KEY (`i_ingresso_comprar`)
    REFERENCES `cinema`.`ingressos` (`i_cod_ingresso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`ofertas` (
  `i_id_ofertas` INT NOT NULL,
  PRIMARY KEY (`i_id_ofertas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinema`.`Bilheteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Bilheteria` (
  `FormaPagamento` INT NOT NULL,
  `compra_id_bilhe` INT NOT NULL,
  `cliente_id_bilhe` INT NOT NULL,
  `mostra_ofertas` INT NULL,
  PRIMARY KEY (`compra_id_bilhe`, `cliente_id_bilhe`, `mostra_ofertas`),
  INDEX `fk_Bilheteria_ofertas1_idx` (`mostra_ofertas` ASC) VISIBLE,
  CONSTRAINT `fk_Bilheteria_comprar1`
    FOREIGN KEY (`compra_id_bilhe`)
    REFERENCES `cinema`.`comprar` (`checaBilhe_comprar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bilheteria_ofertas1`
    FOREIGN KEY (`mostra_ofertas`)
    REFERENCES `cinema`.`ofertas` (`i_id_ofertas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`cliente` (
  `i_id_cliente` INT NOT NULL,
  `s_nome_cliente` VARCHAR(15) NOT NULL,
  `d_dataNas_cliente` DATE NOT NULL,
  `i_tipo_cliente` INT NOT NULL,
  PRIMARY KEY (`i_id_cliente`),
  INDEX `fk_cliente` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `cinema`.`tipocliente` (`i_id_TCliente`),
  CONSTRAINT `fk_cliente_Bilheteria1`
    FOREIGN KEY (`i_id_cliente`)
    REFERENCES `cinema`.`Bilheteria` (`cliente_id_bilhe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
