# Generated by Django 4.1.3 on 2022-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='foto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='tipo',
            field=models.CharField(choices=[('preestreia', 'Pre-Estreia'), ('estreia', 'Estreia')], max_length=10),
        ),
    ]
