# Generated by Django 4.1.3 on 2022-12-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_filme_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='cartaz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
