# Generated by Django 4.1.3 on 2022-12-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_filme_cartaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='tipo',
            field=models.CharField(choices=[('preestreia', 'Pre-Estreia'), ('cartaz', 'Cartaz')], max_length=10),
        ),
    ]
