# Generated by Django 4.1.3 on 2022-12-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_lanche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanche',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='filme',
            name='tipo',
            field=models.CharField(choices=[('cartaz', 'Cartaz'), ('preestreia', 'Pre-Estreia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lanche',
            name='tipo',
            field=models.CharField(choices=[('refeicao', 'Refeicao'), ('bebida', 'Bebida'), ('acompanhamento', 'Acompanhamento')], max_length=15),
        ),
    ]
