# Generated by Django 4.1.4 on 2022-12-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_alter_lanche_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanche',
            name='tipo',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('acompanhamento', 'Acompanhamento'), ('refeicao', 'Refeicao')], max_length=15),
        ),
    ]
