# Generated by Django 4.1.4 on 2022-12-07 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_filme_tipo_alter_lanche_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atores',
            fields=[
                ('i_id_atoresfilme', models.IntegerField(db_column='i_id_atoresFilme', primary_key=True, serialize=False)),
                ('s_nome_ator', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'atores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('i_id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('s_nome_cliente', models.CharField(max_length=15)),
                ('d_datanas_cliente', models.DateField(db_column='d_dataNas_cliente')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estreias',
            fields=[
                ('i_idestreia_est', models.IntegerField(db_column='i_idEstreia_est', primary_key=True, serialize=False)),
                ('d_dataestreia_est', models.DateField(db_column='d_dataEstreia_est')),
                ('ingressos_i_cod_ingresso', models.IntegerField()),
            ],
            options={
                'db_table': 'estreias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingressos',
            fields=[
                ('i_cod_ingresso', models.IntegerField(primary_key=True, serialize=False)),
                ('f_preco_ingresso', models.IntegerField()),
                ('i_id_estreia', models.IntegerField()),
            ],
            options={
                'db_table': 'ingressos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lanches',
            fields=[
                ('i_cod_lanche', models.IntegerField(primary_key=True, serialize=False)),
                ('f_preco_lanche', models.FloatField()),
                ('i_quantidade_lanche', models.IntegerField()),
                ('i_tipo_lanche', models.IntegerField()),
            ],
            options={
                'db_table': 'lanches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id_ofertas', models.IntegerField()),
                ('ofertas', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ofertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('i_cod_sala', models.IntegerField(primary_key=True, serialize=False)),
                ('i_capa_sala', models.IntegerField()),
                ('i_poltrona_sala', models.IntegerField()),
                ('i_numero_sala', models.IntegerField()),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secoes',
            fields=[
                ('i_cod_secoes', models.IntegerField(primary_key=True, serialize=False)),
                ('d_data_secoes', models.DateField()),
                ('h_hora_secoes', models.DateTimeField()),
            ],
            options={
                'db_table': 'secoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocliente',
            fields=[
                ('i_id_tcliente', models.IntegerField(db_column='i_id_TCliente', primary_key=True, serialize=False)),
                ('s_desc_tcliente', models.CharField(blank=True, db_column='s_desc_TCliente', max_length=15, null=True)),
            ],
            options={
                'db_table': 'tipocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipofilme',
            fields=[
                ('i_idcategoria_tipofilme', models.IntegerField(db_column='i_idCategoria_TipoFilme', primary_key=True, serialize=False)),
                ('s_genero_tipofilme', models.CharField(db_column='s_genero_TipoFilme', max_length=5)),
            ],
            options={
                'db_table': 'tipofilme',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Lanche',
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Bilheteria',
            fields=[
                ('formapagamento', models.IntegerField(db_column='FormaPagamento')),
                ('cliente_id_bilhe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='cliente_id_bilhe', serialize=False, to='cinema.cliente')),
                ('mostra_ofertas', models.IntegerField()),
            ],
            options={
                'db_table': 'bilheteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('i_ingresso_comprar', models.OneToOneField(db_column='i_ingresso_comprar', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cinema.ingressos')),
            ],
            options={
                'db_table': 'comprar',
                'managed': False,
            },
        ),
    ]
