# Generated by Django 4.1.4 on 2022-12-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_atores_cliente_estreias_ingressos_lanches_ofertas_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filme',
            table='filme',
        ),
    ]
