# Generated by Django 4.1.4 on 2022-12-17 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_filme_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id_ator', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('data_nascimento_ator', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'itens_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertasCinema',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('id_filme', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
            options={
                'db_table': 'ofertas_cinema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'db_table': 'salas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoingresso',
            fields=[
                ('id_tipoingresso', models.IntegerField(db_column='id_tipoIngresso', primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoingresso',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Atores',
        ),
        migrations.RemoveField(
            model_name='bilheteria',
            name='cliente_id_bilhe',
        ),
        migrations.RemoveField(
            model_name='comprar',
            name='i_ingresso_comprar',
        ),
        migrations.DeleteModel(
            name='Estreias',
        ),
        migrations.DeleteModel(
            name='Lanches',
        ),
        migrations.DeleteModel(
            name='Ofertas',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Tipofilme',
        ),
        migrations.CreateModel(
            name='AtorFilme',
            fields=[
                ('ator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cinema.ator')),
            ],
            options={
                'db_table': 'ator_filme',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bilheteria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comprar',
        ),
    ]
